### PR TITLE
Automatic Swagger API generation

### LINKED ISSUE #55: Consider use of auto-generated API spec/documentation from backend
Enforcing consistency between swagger and backend has proved a bit troublesome, so it could be worth looking at possibilities for auto-generating the API from backend as it now has taken form.

### PR DESCRIPTION
**Pull request by kalkins**
Uses the `drf-yasg` package to generate a Swagger API from the python code. The API is available at `/swagger/`.

This does not solve all our API problems. The code is somewhat advanced, in a way that the generator cannot natively understand. I've tried to override the default generator to mitigate this, but we still have to specify some things manually.

There are also some small bugs, like the `RecurringTransaction` object being named `Object`. I have no idea how to fix these, but they aren't critical.

Fixes #55

### CODE REVIEW

**Comment by kalkins** [comment]
This branch has been deployed, so the you can see the generated API here: http://liquidator.kodeworks.nl/swagger/

**Review by nicomni — APPROVED** [review]
👍

**Comment by nicomni** [comment]
> This branch has been deployed, so the you can see the generated API here: [http://liquidator.kodeworks.nl/swagger](http://liquidator.kodeworks.nl/swagger/)

🚨 	**404 Not Found**

**Comment by kalkins** [comment]
The deployment doesn't work anymore, @FredrikAugust broke it

**Comment by FredrikAugust** [comment]
Typical backend - blaming the innocents.

**Review by FredrikAugust — APPROVED** [review]

**Pull request merged**
